# Generated by Django 2.1.7 on 2019-03-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='statue',
            new_name='status',
        ),
    ]
