# Generated by Django 2.1.7 on 2019-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='create_timed',
        ),
    ]
